name: Update data
on:
  schedule:
    - cron: '0 14 * * *'
jobs:
  update:
    name: update data
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
        with:
          ref: master
          lfs: true
      - name: install lfs
        run: |
          curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
          git lfs install
      - name: setup python
        uses: actions/setup-python@v1
        with:
          python-version: '3.6'
      - name: install python and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r update/requirements.txt
      - name: install fonts for plots
        run: |
          wget "https://mauforonda.gitlab.io/open/otro/quicksand.zip" -O /usr/share/fonts/quicksand.zip
          unzip /usr/share/fonts/quicksand.zip -d /usr/share/fonts/
          fc-cache -f -v
      - name: run script
        run: |
          echo ::set-output name=results::$(python update/update.py)
        id: run_script
      - name: commit
        env:
          DAY: ${{ steps.run_script.outputs.results }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.email "covid19-bot@example.com"
          git config --global user.name "covid19-bot"
          git add -A
          git status
          git commit -m "[ci] $DAY"
          git push -q "https://$GH_TOKEN@github.com/mauforonda/covid19-lapaz.git" master
